#!/usr/bin/env python3
"""
Build Qwen-Agent delta-only addendum by comparing latest Qwen-Agent audit outputs
to previous committed baseline in artifacts/audit/baselines/qwen/.
Writes: artifacts/audit/QWEN_DELTA_ADDENDUM.md, artifacts/audit/qwen_delta.json.
If no baseline exists, generate initial baseline and mark addendum as bootstrap run.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from datetime import datetime

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
AUDIT_DIR = REPO_ROOT / "artifacts" / "audit"
BASELINE_DIR = AUDIT_DIR / "baselines" / "qwen"
QWEN_AGENT = REPO_ROOT / "Qwen-Agent"


def get_qwen_audit_snapshot() -> dict:
    """Produce a minimal audit snapshot for Qwen-Agent (files present, key paths)."""
    snapshot = {"timestamp": datetime.utcnow().isoformat() + "Z", "root": str(QWEN_AGENT), "exists": QWEN_AGENT.exists()}
    if not QWEN_AGENT.exists():
        snapshot["paths"] = []
        snapshot["workflows"] = []
        return snapshot
    paths = []
    for p in QWEN_AGENT.rglob("*"):
        if p.is_file() and ".git" not in p.parts:
            rel = p.relative_to(QWEN_AGENT)
            paths.append(str(rel))
    snapshot["paths"] = sorted(paths)[:500]
    snapshot["workflows"] = [p for p in paths if p.startswith(".github/workflows/")]
    return snapshot


def load_baseline() -> dict | None:
    baseline_file = BASELINE_DIR / "snapshot.json"
    if not baseline_file.exists():
        return None
    try:
        return json.loads(baseline_file.read_text(encoding="utf-8"))
    except Exception:
        return None


def save_baseline(snapshot: dict) -> None:
    BASELINE_DIR.mkdir(parents=True, exist_ok=True)
    (BASELINE_DIR / "snapshot.json").write_text(json.dumps(snapshot, indent=2), encoding="utf-8")


def compute_delta(current: dict, baseline: dict | None) -> dict:
    if not baseline:
        return {
            "bootstrap": True,
            "message": "No prior baseline; this run is bootstrap.",
            "current_paths_count": len(current.get("paths", [])),
            "new_gaps": [],
            "resolved_gaps": [],
            "ownership_shifts": [],
            "workflow_drift": [],
        }
    old_paths = set(baseline.get("paths") or [])
    new_paths = set(current.get("paths") or [])
    added = sorted(new_paths - old_paths)
    removed = sorted(old_paths - new_paths)
    old_wf = set(baseline.get("workflows") or [])
    new_wf = set(current.get("workflows") or [])
    wf_added = sorted(new_wf - old_wf)
    wf_removed = sorted(old_wf - new_wf)
    return {
        "bootstrap": False,
        "new_gaps": added[:50],
        "resolved_gaps": removed[:50],
        "workflow_drift": wf_added + ["- " + x for x in wf_removed],
        "current_paths_count": len(new_paths),
        "baseline_paths_count": len(old_paths),
    }


def write_addendum_md(delta: dict) -> None:
    lines = [
        "# Qwen-Agent Delta Addendum",
        "",
        "Delta-only view vs prior baseline. Generated by build_qwen_delta_addendum.py.",
        "",
    ]
    if delta.get("bootstrap"):
        lines.extend(["## Bootstrap run", "", "No prior baseline; this run established the baseline.", ""])
    else:
        lines.append("## Changes")
        if delta.get("new_gaps"):
            lines.append("### New / added paths (sample)")
            for p in delta["new_gaps"][:30]:
                lines.append(f"- {p}")
            lines.append("")
        if delta.get("resolved_gaps"):
            lines.append("### Removed / resolved paths (sample)")
            for p in delta["resolved_gaps"][:30]:
                lines.append(f"- {p}")
            lines.append("")
        if delta.get("workflow_drift"):
            lines.append("### Workflow drift")
            for w in delta["workflow_drift"][:20]:
                lines.append(f"- {w}")
            lines.append("")
    (AUDIT_DIR / "QWEN_DELTA_ADDENDUM.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    current = get_qwen_audit_snapshot()
    baseline = load_baseline()
    delta = compute_delta(current, baseline)
    if delta.get("bootstrap"):
        save_baseline(current)
    write_addendum_md(delta)
    (AUDIT_DIR / "qwen_delta.json").write_text(json.dumps(delta, indent=2), encoding="utf-8")
    print("Wrote QWEN_DELTA_ADDENDUM.md and qwen_delta.json")
    return 0


if __name__ == "__main__":
    sys.exit(main())
