"""Recommendation report — JSON and Markdown output."""

import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List


REPO_ROOT = Path(__file__).resolve().parent.parent


def generate_json_report(ranked_candidates: List[Dict[str, Any]], output_dir: Path) -> Path:
    """
    Generate ranked.json with all fields.

    Returns path to generated file.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    output_file = output_dir / "ranked.json"

    report = {
        "metadata": {
            "generated_at": datetime.now().isoformat(),
            "total_candidates_scored": len(ranked_candidates),
            "recommender_version": "1.0.0",
        },
        "candidates": [
            {
                "position": c.get("position"),
                "candidate_id": c.get("candidate_id"),
                "persona": c.get("persona"),
                "topic": c.get("topic"),
                "teacher": c.get("teacher"),
                "language": c.get("language"),
                "format": c.get("format"),
                "city_overlay": c.get("city_overlay"),
                "score": c.get("score"),
                "reason_codes": c.get("reason_codes", []),
                "slot_type": c.get("slot_type"),
            }
            for c in ranked_candidates
        ]
    }

    with open(output_file, "w") as f:
        json.dump(report, f, indent=2)

    return output_file


def generate_markdown_report(ranked_candidates: List[Dict[str, Any]], output_dir: Path) -> Path:
    """
    Generate summary.md with human-readable format.

    Returns path to generated file.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    output_file = output_dir / "summary.md"

    # Extract diversity metrics if present
    diversity_metrics = {}
    if ranked_candidates:
        diversity_metrics = ranked_candidates[0].get("_diversity_metrics", {})

    # Separate exploit and explore
    exploit = [c for c in ranked_candidates if c.get("slot_type") == "exploit"]
    explore = [c for c in ranked_candidates if c.get("slot_type") == "explore"]

    lines = [
        "# Phoenix Recommender v1 — Recommendations",
        "",
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "## Summary",
        "",
        f"- Total candidates evaluated: {len(ranked_candidates)}",
        f"- Exploit slots (high confidence): {len(exploit)}",
        f"- Explore slots (discovery): {len(explore)}",
        "",
    ]

    # Diversity section
    if diversity_metrics:
        lines.extend([
            "## Diversity Metrics",
            "",
            f"- Unique personas: {diversity_metrics.get('unique_personas', '?')}",
            f"- Unique topics: {diversity_metrics.get('unique_topics', '?')}",
            f"- Unique teachers: {diversity_metrics.get('unique_teachers', '?')}",
            "",
        ])

    # Rankings table
    lines.extend([
        "## Ranked Candidates",
        "",
        "| Position | Candidate ID | Persona | Topic | Teacher | Language | Format | City | Score | Reasons | Slot |",
        "|----------|------------|---------|-------|---------|----------|--------|------|-------|---------|------|",
    ])

    for c in ranked_candidates:
        reason_str = ", ".join(c.get("reason_codes", [])[:2])  # Limit to 2 for brevity
        lines.append(
            f"| {c.get('position', '?')} | `{c.get('candidate_id', '?')}` | "
            f"{c.get('persona', '?')} | {c.get('topic', '?')} | {c.get('teacher', '?')} | "
            f"{c.get('language', '?')} | {c.get('format', '?')} | {c.get('city_overlay', '?')} | "
            f"{c.get('score', 0):.4f} | {reason_str} | {c.get('slot_type', '?')} |"
        )

    lines.extend(["", "## Exploration Strategy", ""])

    # Explanation of explore slots
    if explore:
        lines.append("### Why These Explore Slots?")
        lines.append("")
        lines.append(
            "Explore slots represent candidates with moderate scores but high potential for discovery. "
            "These candidates may serve underserved segments or represent emerging demand signals."
        )
        lines.append("")

        for c in explore:
            lines.append(f"- **{c['candidate_id']}** ({c['persona']} × {c['topic']}): "
                        f"{', '.join(c.get('reason_codes', ['no_reasons']))}")

    lines.extend(["", "---", ""])
    lines.append("*Report generated by Phoenix Recommender v1.0*")

    markdown = "\n".join(lines)
    with open(output_file, "w") as f:
        f.write(markdown)

    return output_file


def generate_reports(ranked_candidates: List[Dict[str, Any]], output_dir: str = None) -> tuple:
    """
    Generate both JSON and Markdown reports.

    Args:
        ranked_candidates: List of ranked candidate dicts
        output_dir: Output directory (default: artifacts/recommendations/)

    Returns:
        (json_path, markdown_path)
    """
    if output_dir is None:
        output_dir = REPO_ROOT / "artifacts" / "recommendations"
    else:
        output_dir = Path(output_dir)

    json_path = generate_json_report(ranked_candidates, output_dir)
    markdown_path = generate_markdown_report(ranked_candidates, output_dir)

    return json_path, markdown_path


def main():
    """Test report generation."""
    sample_ranked = [
        {
            "position": 1,
            "candidate_id": "abc123",
            "persona": "gen_z_professionals",
            "topic": "anxiety",
            "teacher": "ahjan",
            "language": "en",
            "format": "core",
            "city_overlay": "nyc",
            "score": 0.75,
            "reason_codes": ["high_demand", "coverage_gap"],
            "slot_type": "exploit",
            "_diversity_metrics": {
                "unique_personas": 8,
                "unique_topics": 12,
                "unique_teachers": 6,
            }
        },
        {
            "position": 2,
            "candidate_id": "def456",
            "persona": "millennial_women_professionals",
            "topic": "burnout",
            "teacher": "miki",
            "language": "ja-JP",
            "format": "companion",
            "city_overlay": "tokyo",
            "score": 0.68,
            "reason_codes": ["coverage_gap"],
            "slot_type": "explore",
        },
    ]

    json_path, md_path = generate_reports(sample_ranked)
    print(f"\n=== Report Generation (Sample) ===")
    print(f"JSON report: {json_path}")
    print(f"Markdown report: {md_path}")
    print("\nGenerated files exist:")
    print(f"  JSON: {json_path.exists()}")
    print(f"  Markdown: {md_path.exists()}")


if __name__ == "__main__":
    main()
